# Generated by Django 3.0 on 2023-04-24 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, null=True)),
                ('buying_price', models.IntegerField()),
                ('selling_price', models.IntegerField()),
                ('product_quantity', models.IntegerField()),
                ('product_image', models.ImageField(null=True, upload_to='products/')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('product_category', models.ForeignKey(db_column='category_name', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=50, null=True)),
                ('service_cost', models.IntegerField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('service_category', models.ForeignKey(db_column='category_name', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('product_price', models.ForeignKey(db_column='selling_price', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_product_prices', to='app.Product')),
                ('products', models.ForeignKey(db_column='product_name', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_products', to='app.Product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Offered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('service', models.ForeignKey(db_column='service_type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offered_service', to='app.Service')),
                ('service_cost', models.ForeignKey(db_column='service_cost', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offered_service_cost', to='app.Service')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('logo', models.ImageField(upload_to='profile/')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
